bot-token: token
admin-key: 12345
main-guild-id: 0
anti-spam:
  count: 10
  time: 3

translations:
  ##### Generals #####
  general:
    not_sent: '**Oops!** An error occurred while sending your message. Please try again later.'
    close_embed: 'Counting channel closed!'
    open_embed:
      title: '**This counting channel is now open!**'
      description: '**Feel free to play with us!**\n\nChannel type: `%s`\nDescription: `%s`'
    unsupported_channel_type: 'This channel\0027s type is not supported.'
    unknown_language: 'Unknown language. Try again.'
    unknown_channel_type: 'Unknown channel type. Try again.'
    status: 'counting channels'
    do_not_spam: 'Do not spam on the counting channel! You can only send %s messages with less than %s seconds between each.'
    incorrect_admin_key: 'Incorrect administrator key!'
    no_permission: 'I don\0027t have all required permissions in this channel.'
  ##### Commands #####
  commands:
    unknown: 'Unknown command.'
    cooldown: 'You can use this command again in %s seconds.'
    error: 'An error occurred. Try again.'
    #ping
    ping:
      name: 'ping'
      description: 'Shows the current ping of the bot'
      option:
        name: 'ephemeral'
        description: 'whether this message should only be visible to you'
        values:
          true: 'True'
          false: 'False'
    #about
    about:
      name: 'about'
      description: 'Shows some basic information about this bot.'
      option:
        name: 'ephemeral'
        description: 'whether this message should only be visible to you'
        values:
          true: 'True'
          false: 'False'
      message: 'TODO'
    #feedback
    feedback:
      name: 'feedback'
      description: 'Report a bug, suggest a change or share your impressions'
      title: 'Send feedback'
      subject: 'Subject'
      subject_placeholder: 'e.g. bug report, suggestion'
      modal_description: 'Description'
      success: 'Thank you for your feedback!'
      failure: 'An error occurred. Try again.'
      open_channels: 'Opened %s channels out of %s!'
    #ranking
    ranking:
      name: 'ranking'
      description: 'Shows users ranking'
      options:
        ephemeral:
          name: 'ephemeral'
          description: 'whether this message should only be visible to you'
          true: 'True'
          false: 'False'
        amount:
          name: 'amount'
          description: 'description'
      title: '**Top %s places**'
      row: '%s %s - %s message(s)'
      empty: 'The ranking is currently empty or an error occurred.'
    ranking_context:
      name: 'ranking'
      empty: 'This user never sent any message or an error occurred.'
      message: '%s has sent `%s` message(s) - `%s` place in ranking.'
      button: 'Send me as not ephemeral'
      success: 'Success!'
      failure: 'This message cannot be sent in this channel.'
    #counting
    counting:
      name: 'counting'
      description: 'Manages the counting channels'
      options:
        add:
          name: 'add'
          description: 'Opens a new counting channel'
        remove:
          name: 'remove'
          description: 'Closes the counting channel'
        list:
          name: 'list'
          description: 'Shows all opened counting channel in this guild'
      add: '**__Select the type of the new counting channel:__**'
      remove:
        success: 'The channel has been successfully closed!'
        no_changes: 'This channel has been already closed.'
        failure: 'An error occurred. Try again.'
      list:
        list: '**__Open Counting Channels:__**'
        empty_list: 'No counting channel has been opened yet. Open a new one with `/counting add`'
    #dictionary
    dictionary:
      name: 'dictionary'
      description: 'Manages dictionaries'
      types:
        polish: 'Polish'
        english: 'English'
        german: 'German'
        spanish: 'Spanish'
      options:
        add:
          name: 'add'
          description: 'Adds a word to the dictionary'
        remove:
          name: 'remove'
          description: 'Removes a word from the dictionary'
        load:
          name: 'load'
          description: 'Loads a file into the dictionary'
        language:
          name: 'language'
          description: 'The dictionary\0027s type'
        word:
          name: 'word'
          description: 'A word to add/remove'
        admin_key:
          name: 'admin-key'
          description: 'The secret administrator key'
        file:
          name: 'file'
          description: 'The dictionary file'
      add:
        success: 'This word has been successfully added to the dictionary in %s ms.'
        failure: 'An error occurred. Try again.'
      remove:
        success: 'This word has been successfully removed from the dictionary in %s ms.'
        failure: 'An error occurred. Try again.'
      load:
        success: 'Success! (%s ms)'
        no_changes: 'This file does not exist.'
        failure: 'An error occurred. Try again.'
    #select menu
    select_menu:
      success: 'The channel has been successfully opened!'
      no_changes: 'This channel is already opened!'
      failure: 'An error occurred. Try again.'
    #delete message
    delete_message:
      name: 'delete this message'
      modal:
        name: 'Confirm your permissions!'
        option: 'Enter an admin-key here:'
      failure:
        no_permission: 'You cannot delete this message.'
        retrieve_message: 'An error occurred while retrieving the message to delete.'
      success: 'Success!'
  ##### Handlers #####
  handlers:
    last_letter:
      incorrect_start_char: '**Oops!** Your message does not start with the last character of the previous message.'
      too_short: '**Oops!** Your message is too short.'
      illegal_char: '**Oops!** Your message contains illegal character: `%s`'
      illegal_end_char: '**Oops!** Your message cannot end with one of the following characters: %s'
      incorrect_word: '**Oops!** This word does not exists in the dictionary or has already been used!'
      failure: '**Oops!** An error occurred while loading dictionary. Try again.'
  ##### Channel types #####
  type:
    counting:
      name: 'Counting'
      description: 'Write next numbers'
    binary_counting:
      name: 'Binary Counting'
      description: 'Write next numbers in binary'
    hexadecimal_counting:
      name: 'Hexadecimal Counting'
      description: 'Write next hexadecimal numbers'
    prime_counting:
      name: 'Prime Counting'
      description: 'Write next prime numbers'
    semiprime_counting:
      name: 'Semiprime counting'
      description: 'Write next semiprime numbers'
    sphenic_counting:
      name: 'Sphenic counting'
      description: 'Write next sphenic numbers'
    fibonacci_sequence:
      name: 'Fibonacci sequence'
      description: 'Write next numbers of the fibonacci sequence'
    lucas_numbers:
      name: 'Lucas numbers'
      description: 'Write next numbers of the lucas sequence'
    triangular_numbers:
      name: 'Triangular numbers'
      description: 'Write next triangular numbers'
    palindromic_numbers:
      name: 'Palindromic numbers'
      description: 'Write next palindromic numbers'
    roman_counting:
      name: 'Roman counting'
      description: 'Write next roman numbers'
    alphabet:
      name: 'Alphabet'
      description: 'Write next letters in english alphabet'
    polish_last_letter:
      name: 'Polish last letter'
      description: 'Write a word that starts with the last letter of the previous one (Polish)'
    english_last_letter:
      name: 'English last letter'
      description: 'Write a word that starts with the last letter of the previous one (English)'
    german_last_letter:
      name: 'German last letter'
      description: 'Write a word that starts with the last letter of the previous one (German)'
    spanish_last_letter:
      name: 'Spanish last letter'
      description: 'Write a word that starts with the last letter of the previous one (Spanish)'