bot-token: token
activity: Counting...
admin-key: 12345
main-guild-id: 0
logs-channel-id: 0
about-message: ''
slowmode: 3
anti-spam:
  count: 10
  time: 3
database:
  host: localhost
  port: 3306
  username: root
  password: password
  database: minecraft
