bot-token: token
admin-key: 12345
main-guild-id: 0
logs-channel-id: 0
anti-spam:
  count: 10
  time: 3

translations:
  general:
    not_sent: '**Oops!** An error occurred while sending your message. Please try again later.'
    close_embed: 'Counting channel closed!'
    open_embed:
      title: '**This counting channel is now open!**'
      description: '**Feel free to play with us!**\n\nChannel type: `%s`\nDescription: `%s`'
    unsupported_channel_type: 'This channel\0027s type is not supported.'
    unknown_language: 'Unknown language. Try again.'
    unknown_channel_type: 'Unknown channel type. Try again.'
    status: 'counting channels'
    do_not_spam: 'Do not spam on the counting channel! You can only send %s messages with less than %s seconds between each.'
  commands:
    about: 'Coming soon!'
    feedback:
      title: 'Send feedback'
      subject: 'Subject'
      subject_placeholder: 'e.g. bug report, suggestion'
      description: 'Description'
      success: 'Thank you for your feedback!'
      failure: 'An error occurred. Try again.'
    counting:
      add: '**Select the type of the new counting channel:**'
      remove:
        success: 'The channel has been successfully closed!'
        no_changes: 'This channel has been already closed.'
        failure: 'An error occurred. Try again.'
      list:
        list: '**Open Counting Channels:**'
        empty_list: 'No counting channel has been opened yet. Open a new one with `/counting add`'
    dictionary:
      add:
        success: 'This word has been successfully added to the dictionary!'
        failure: 'An error occurred. Try again.'
      remove:
        success: 'This word has been successfully removed from the dictionary!'
        failure: 'An error occurred. Try again.'
      load:
        incorrect_key: 'Incorrect administrator key!\nThe admin-key can be found in the configuration file. This is to prevent uploading random files by people who do not have access to them.'
        success: 'Success!'
        no_changes: 'This file does not exist.'
        failure: 'An error occurred. Try again.'
    select_menu:
      success: 'The channel has been successfully opened!'
      no_changes: 'This channel is already opened!'
      failure: 'An error occurred. Try again.'
  handlers:
    last_letter:
      incorrect_start_char: '**Oops!** Your message does not start with the last character of the previous message.'
      too_short: '**Oops!** Your message is too short.'
      illegal_char: '**Oops!** Your message contains illegal character: `%s`'
      illegal_end_char: '**Oops!** Your message cannot end with one of the following characters: %s'
      incorrect_word: '**Oops!** This word does not exists in the dictionary or has already been used!'
      failure: '**Oops!** An error occurred while loading dictionary. Try again.'
  type:
    counting:
      name: 'Counting'
      description: 'Write the next numbers'
    binary_counting:
      name: 'Binary Counting'
      description: 'Write the next numbers in binary'
    hexadecimal_counting:
      name: 'Hexadecimal Counting'
      description: 'Write next hexadecimal numbers.'
    prime_counting:
      name: 'Prime Counting'
      description: 'Write the next prime numbers'
    semipime_counting:
      name: 'Semiprime counting'
      description: 'Write the next semiprime numbers'
    sphenic_counting:
      name: 'Sphenic counting'
      description: 'Write the next sphenic numbers'
    fibonacci_sequence:
      name: 'Fibonacci sequence'
      description: 'Write the next numbers of the fibonacci sequence'
    lucas_numbers:
      name: 'Lucas numbers'
      description: 'Write the next numbers of the lucas sequence'
    triangular_numbers:
      name: 'Triangular numbers'
      description: 'Write the next triangular numbers'
    palindromic_numbers:
      name: 'Palindromic numbers'
      description: 'Write the next palindromic numbers'
    alphabet:
      name: 'Alphabet'
      description: 'Write the next letters in english alphabet'
    polish_last_letter:
      name: 'Polish last letter'
      description: 'Write a word that starts with the last letter of the previous one (Polish)'
    english_last_letter:
      name: 'English last letter'
      description: 'Write a word that starts with the last letter of the previous one (English)'
    german_last_letter:
      name: 'German last letter'
      description: 'Write a word that starts with the last letter of the previous one (German)'
    spanish_last_letter:
      name: 'Spanish last letter'
      description: 'Write a word that starts with the last letter of the previous one (Spanish)'
